const PostsActionTypes = {
  TOGGLE_POST_SELECTED: 'TOGGLE_POST_SELECTED',
  DISMISS_POST: 'DISMISS_POST',
  DISMISS_ALL: 'DISMISS_ALL',
  FETCH_POSTS_START: 'FETCH_POSTS_START',
  FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
  FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',
};

export default PostsActionTypes;
